# Dependabot configuration for this repository.

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "typescript"
        versions:
          - ">=6.0.0" # This ignores all versions 6.0.0 and above
